# Generated by Django 5.0 on 2023-12-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_form_current_role_form_recommend_form_useful'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
            ],
        ),
    ]
