# Generated by Django 5.0 on 2023-12-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_form_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='current_role',
            field=models.CharField(choices=[('student', 'student'), ('job', 'job'), ('learner', 'learner')], default='default_role_value', max_length=80),
        ),
    ]
