# Generated by Django 5.0 on 2023-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_form_current_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='username',
            field=models.CharField(default='default_role_value', max_length=100),
        ),
    ]
