# Generated by Django 5.0 on 2023-12-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_remove_form_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='username',
            field=models.CharField(default='superuser', max_length=100),
        ),
    ]
